language: java

jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
sudo: required

services:
  - postgresql

script: mvn test

before_script:
  - psql -c "create database tipsters;" -U postgres

cache:
  directories:
  - $HOME/.m2
