
server:
  context-path: /api/tipsters
  port: 19000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tipsters
    username: postgres
    password: root
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    cache-names: matchesByCompetitions
    guava:
      spec: "maximumSize=100,expireAfterAccess=20m,expireAfterWrite=30m"

tipsters:
  willHillFeedUrl: http://cachepricefeeds.williamhill.com/

logging.level.: INFO
logging.level:
  io.tipsters: DEBUG
