
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS leagues;

CREATE TABLE leagues (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE teams (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  league_id UUID REFERENCES leagues(id) NOT NULL
);
